### ISSUE TITLE
custom image with GPU and Nvidia driver cannot be restarted

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_custom_ai_platform_notebook#10]

**Comment by tarrade** [comment]
I found some issue with my custom AI Platform image. I am using `tf-gpu:m43` as based image. I am using all the option needed (installing nvidia driver, terminate policy, restart on failure ..).
https://github.com/tarrade/proj_custom_ai_platform_notebook/blob/master/deployment/notebook-instance-optimized-template.jinja

At this stage no GPU are attached. The build is working fine and I can see my AI Platform note book with CPU. I can open the notebook link and everything is working fine.

I stop this instance and attached a GPU. I start this instance with GPU. Everything is working. I can open the notebook and see that GPU is now available.
```
CONTAINER ID        IMAGE                                                                       COMMAND                  CREATED             STATUS              PORTS               NAMES

60f3ce84b1fc            gcr.io/inverting-proxy/agent                                        "/bin/sh -c '/opt/bi…"     3 minutes ago       Up 3 minutes                                   proxy-agent

db3548349c49          gcr.io/axarevvicnonprod/derived-tf-gpu:dev-v2.0.2    "/entrypoint.sh /run…"   4 minutes ago       Up 3 minutes                                   payload-container
```

I stop this instance and removed the GPU. I restarted the instance without GCPU. The link to access the notebook is not working any more (504. That’s an error.)

If I SSH the underlying event, I see no custom container running ! I was not able to see anything in the various logs.

```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES

ed2a2667361a          gcr.io/inverting-proxy/agent   "/bin/sh -c '/opt/bi…"      4 minutes ago        Up 4 minutes                                  proxy-agent

```

the container is not running. Normally the container is suppose to restart on failure but it seems the issue happen before. If I stop again the instance re-attached the GPU, everything is working again!

Without better, I tried to run the scrip that load the container:
`. /opt/deeplearning/bin/load_container.sh  2>&1 | tee log.txt`

and now I can see the issue:
`dev-v2.0.2: Pulling from axarevvicnonprod/derived-tf-gpuDigest: sha256:bb6427e88098087921c559035fee0f7d309104550687d4d12cb1885ab34e38cdStatus: Image is up to date for gcr.io/xxx/derived-tf-gpu:dev-v2.0.2gcr.io/xxx/derived-tf-gpu:dev-v2.0.2docker: Error response from daemon: Conflict. The container name "/payload-container" is already in use by container "xxx608cfe0488cdea93235a779b0c680ac1f627c281". You have to remove (or rename) that container to be able to reuse that name.See 'docker run --help'`.
by just doing:

`docker rm "/payload-container"`

this solve the issue and everything is working fine

Did I missed to add some option in my jinja scrip for such case ?

Sure I can add this line `'docker rm "/payload-container"'`   in the script `'/opt/deeplearning/bin/load_container.sh'` before `'docker run -d …'.`  (I am already adding -p 6006 for TensorBoard)

**Comment by tarrade** [comment]
issue fix with the script. Let see if Slava propose a better solution

**Comment by YuxuanChen** [comment]
Hi @tarrade,

The script `/opt/deeplearning/bin/load_container.sh` already has logic for this:

```
readonly CONTAINER_NAME="payload-container"
if [ "$(docker ps -q -f name=${CONTAINER_NAME})" ]; then
    docker stop ${CONTAINER_NAME}
    docker rm ${CONTAINER_NAME}
fi
```

Do you know if this only happens when you reattach/detach GPUs? Are you able to consistently reproduce this issue?

**Comment by tarrade** [comment]
Hi @YuxuanChen ,

yes the issue one year ago was when detaching GPU to go back to CPU. I added the famous line and informed Slava. I didn't pay attention that it was fixed. I gave a try and as you said, it i not needed anymore. Great.

New version of the startup script looks like that (the code is now in some Github Entreprise repo)

```
#!/bin/bash

# Print env variable and check
echo "checking if env variables exist ..."
printenv

# trick to fix authorization issue
echo "config for Artifact Registry to upload container ..."
gcloud beta auth configure-docker europe-west4-docker.pkg.dev

# check config load_container.sh
echo "display load_container.sh"
cat /opt/deeplearning/bin/load_container.sh

echo "checking if .vm_created exist ..."
if [ ! -f /.vm_created ]; then

  # adding port forwarding for TensorBoard/VS Code and other on port 6006-6016
  # add port-forwarding instructions for SSH into container
  echo "forward port 6006-6016"
  sed -i '/docker run -d/a\    -p 127.0.0.1:6006-6016:6006-6016/tcp \\' /opt/deeplearning/bin/load_container.sh
  sed -i '/docker run -d/a\    -p 0.0.0.0:2222:2222/tcp \\' /opt/deeplearning/bin/load_container.sh

  # not needed anymore. Info from Chen 05.05.2021
  #sed -i '/docker run -d/i\docker rm "/payload-container" || printf "no existing payload container to be deleted"\' /opt/deeplearning/bin/load_container.sh

  echo "check modification on load_container.sh"
  cat /opt/deeplearning/bin/load_container.sh

  # created a file to indicate the VM was created
  touch /.vm_created

  echo "rebooting now to ensure port-forwarding rules are enabled"
  reboot
else
  echo "everything already exist ..."
fi
```

Since I am using Artifact Registry I need this tricks: 
"gcloud beta auth configure-docker europe-west4-docker.pkg.dev" do you know if this is solve ?

Also with the new M67 (maybe it was here before) I see Warning with Nvidia stuff:

```
[   32.371262] rc.local[412]: Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 450.80.02................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
May  5 06:16:18 test-payload-fabien-tarrade-2021-05-05-at-07-37 rc.local[412]: Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 450.80.02................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[   32.831711] rc.local[412]: WARNING: The nvidia-drm module will not be installed. As a result, DRM-KMS will not function with this installation of the NVIDIA driver.
May  5 06:16:19 test-payload-fabien-tarrade-2021-05-05-at-07-37 rc.local[412]: WARNING: The nvidia-drm module will not be installed. As a result, DRM-KMS will not function with this installation of the NVIDIA driver.
[   32.861317] rc.local[412]: WARNING: nvidia-installer was forced to guess the X library path '/usr/lib64' and X module path '/usr/lib64/xorg/modules'; these paths were not queryable from the system.  If X fails to find the NVIDIA X driver module, please install the `pkg-config` utility and the X.Org SDK/development package for your distribution and reinstall the driver.
May  5 06:16:19 test-payload-fabien-tarrade-2021-05-05-at-07-37 rc.local[412]: WARNING: nvidia-installer was forced to guess the X library path '/usr/lib64' and X module path '/usr/lib64/xorg/modules'; these paths were not queryable from the system.  If X fails to find the NVIDIA X driver module, please install the `pkg-config` utility and the X.Org SDK/development package for your distribution and reinstall the driver.
```

This is probably only Warning and nothing to worry about.

Thanks for jupming in this thread and updating me about the update.
