### ISSUE TITLE
fix warning with creation of AI Platform notebook:  "Disk size: '100 GB' is larger than image size: '50 GB'.

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_custom_ai_platform_notebook#9]
WARNING: Create operation operation-1587157079430-5a382cdec16d0-b2ee2c0c-86daa9dc 
 code: EXTERNAL_API_WARNING
 data:
 - key: disk_size_gb
  value: '100'
- key: image_size_gb
  value: '50'
 message: "Disk size: '100 GB' is larger than image size: '50 GB'. You might need to\
   \ resize the root repartition manually if the operating system does not support\
   \ automatic resizing. See https://cloud.google.com/compute/docs/disks/add-persistent-disk#resize_pd\
   \ for details."

**Comment by tarrade** [comment]
bug report here:
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/422

**Comment by tarrade** [comment]
ticket open on GCP support side

**Comment by rubber-ant** [comment]
any update?

**Comment by tarrade** [comment]
I don't see this error with the recent GCP SDK when using "gcloud notebook instance create xxx". I am using a intern repo with a different setup.
